name: Build SM8750 (Mesa experiment)

on:
  push:
    branches: [mesa-experiment]
    paths:
      - 'projects/ROCKNIX/packages/graphics/mesa/**'
      - '.github/workflows/build-sm8750-mesa.yml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-device.yml
    secrets: inherit
    with:
      PROJECT: ROCKNIX
      DEVICE: SM8750
      OWNER_LC: ddordie
      NIGHTLY: "true"
      OFFICIAL: "false"
